backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Stránky"
    files:
      - name: "home"
        label: "Úvodní stránka"
        file: "src/pages/index.astro"
        fields:
          - { label: "Nadpis", name: "heroTitle", widget: "string" }
          - { label: "Text", name: "heroText", widget: "text" }
