backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

locale: "cs"

collections:
  - name: "content"
    label: "Obsah Webu"
    files:
      - name: "home"
        label: "Domovská stránka"
        file: "src/pages/index.astro"
        fields:
          - {label: "Hlavní nadpis (Hero)", name: "heroTitle", widget: "string", default: "Kreativita a efektivita bez bull****"}
          - {label: "Podtitul", name: "heroSubtitle", widget: "text", default: "Specializujeme se na sociální sítě..."}
