backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

locale: "cs"

collections:
  - name: "pages"
    label: "Stránky"
    files:
      - name: "home"
        label: "Domovská stránka"
        file: "src/data/home.json"
        fields:
          - {label: "Hlavní Nadpis", name: "heroTitle", widget: "string"}
          - {label: "Podtitul (Perex)", name: "heroSubtitle", widget: "text"}
          - {label: "Tlačítko 1", name: "buttonWork", widget: "string"}
          - {label: "Tlačítko 2", name: "buttonContact", widget: "string"}
